BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "lists" (
	"id"	INTEGER NOT NULL,
	"title"	TEXT NOT NULL,
	"board_id"	INTEGER NOT NULL,
	"order"	INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY("id"),
	FOREIGN KEY("board_id") REFERENCES "boards"("id") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "notes" (
	"id"	INTEGER NOT NULL,
	"list_id"	INTEGER NOT NULL,
	"minimized"	INTEGER NOT NULL DEFAULT 0,
	"raw"	INTEGER NOT NULL DEFAULT 0,
	"text"	TEXT NOT NULL,
	"order"	INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY("id"),
	FOREIGN KEY("list_id") REFERENCES "lists"("id") ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS "boards" (
	"id"	INTEGER NOT NULL,
	"title"	TEXT,
	PRIMARY KEY("id")
);
COMMIT;
